/* Intervenciones Quirurgicas - Suspendidas . para Ana SubGerenta de Análisis ... */

SELECT
T.SOLOPECENASICOD                         AS CENTRO,
T.SOLOPESERVHOSCOD                        AS CODSERVPROCED,
(SELECT X.SERVHOSDES  FROM CMSHO10 X
 WHERE X.SERVHOSCOD = T.SOLOPESERVHOSCOD) AS SERV_PROCEDENCIA,
D.ACTMEDEDADATEN                          AS EDAD,
M.TIPSEGDES                               AS TIPO_SEGURO,
N.TIPOPACINOM                             AS TIPO_PACIENTE,
T.SOLOPENUM                               AS NUM_SOLICITUD,
TO_CHAR(T.SOLOPEFEC, 'dd/mm/yyyy')        AS FECHA_SOLICITUD,
TO_CHAR(T.SOLOPESOLFEC, 'dd/mm/yyyy')     AS FECHA_PROGRAMACION,
O.SOLOPEDIAGCOD                           AS COD_DIAG,
(SELECT Z.DIAGDES FROM CMDIA10 Z
 WHERE Z.DIAGCOD = O.SOLOPEDIAGCOD)       AS DIAGNOSTICO,
       F.CPSCOD AS CPT_OPERACION,
 REPLACE(REPLACE(TRIM(F.CPSDES),
 CHR(10), ''), CHR(13), '')               AS DESCRIPCION, -- se upd
G.GRDCMCCOD                               AS COD_COMPLEJIDAD,
G.GRDCMCDES                               AS COMPLEJIDAD,
T.MOTSOPCOD                                                AS CODMOTSUSPENSION,
(SELECT R.MOTSOPDES FROM SGSS.QBMSO10 R
 WHERE R.MOTSOPCOD = T.MOTSOPCOD)                          AS MOTIVO_SUSPENSION,
TO_CHAR(T.SOLOPEMODFEC, 'dd/mm/yyyy')                      AS FECMODIF,
T.SOLOPECENQUICOD                                          AS COD_QUIROF,
T.SOLOPESOLSERVHOSCOD                                      AS SERVQUI_SOLICITADA,
(SELECT X.SERVHOSDES FROM CMSHO10 X
 WHERE X.SERVHOSCOD = T.SOLOPESOLSERVHOSCOD)               AS DESSERVQUI_SOLIC,
(SELECT SQ.SALOPEDES FROM QMCQS10 SQ
        WHERE T.SOLOPESALOPECOD = SQ.SALOPECOD
        AND ROWNUM = 1)                                    AS DESC_SALA
FROM QTSOP10 T
LEFT OUTER JOIN QTSOD10 O ON T.SOLOPEORICENASICOD = O.SOLOPEORICENASICOD
                         AND T.SOLOPECENASICOD = O.SOLOPECENASICOD
                         AND T.SOLOPENUM = O.SOLOPENUM
LEFT OUTER JOIN QTSOO10 C ON T.SOLOPEORICENASICOD = C.SOLOPEORICENASICOD
                         AND T.SOLOPECENASICOD = C.SOLOPECENASICOD
                         AND T.SOLOPENUM = C.SOLOPENUM
LEFT OUTER JOIN CMAME10 D ON T.SOLOPEORICENASICOD = D.ORICENASICOD
                         AND T.SOLOPECENASICOD = D.CENASICOD
                         AND T.SOLOPEACTMEDNUM = D.ACTMEDNUM
LEFT OUTER JOIN CMPER10 E ON D.ACTMEDPACSECNUM = E.PERSECNUM
LEFT OUTER JOIN CBTPC10 N ON D.ACTMEDTIPOPACICOD = N.TIPOPACICOD
LEFT OUTER JOIN CMTSE10 M ON D.ACTMEDTIPSEGCOD = M.TIPSEGCOD
LEFT OUTER JOIN CMCPP10 F ON C.SOLOPECPSCOD = F.CPSCOD
LEFT OUTER JOIN QBGCC10 G ON F.GRDCMCCOD = G.GRDCMCCOD
WHERE  TO_CHAR(T.Solopeprofec,'yyyymmdd') >= &P_FECHAINICIO
  AND TO_CHAR(T.Solopeprofec,'yyyymmdd') <= &P_FECHAFIN
  AND T.ESTSOPCOD = '3';